app = "oudla"
primary_region = "gru"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  NODE_OPTIONS = "--max-old-space-size=512"

[processes]
  app = "npm start"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # Não desliga
  auto_start_machines = true
  min_machines_running = 2    # Máximo possível 100% grátis
  processes = ["app"]

[checks]
  [checks.alive]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/"
    port = 3000
    timeout = "10s"
    type = "http"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
